exclude: ^(\.ruff_cache|\.venv)/

default_language_version:
  python: python3.13

repos:
  # Python linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
      - id: ruff-check
        args: [--fix, --config, pyproject.toml]
        files: ".*\\.py$"
      - id: ruff-format
        args: [--config, pyproject.toml]
        files: ".*\\.py$"

  # Python type checking
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [python]
        files: ".*\\.py$"
        pass_filenames: false

  # Final hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
